### ISSUE TITLE
ReadMe instructions not clear

### ISSUE THREAD

**Issue by avinashxx3** [udaykiran183/CLUBS_IITK#1]
Installing the software using the instructions provided in the readme file doesn't work. It only works after removing the root password in the /config/constants.php file.
![image](https://user-images.githubusercontent.com/76612206/163727097-5a709338-a811-4be9-8875-05fe26702249.png)
![image](https://user-images.githubusercontent.com/76612206/163727103-e62ba626-cb98-4f84-ad23-453986009e40.png)

**Comment by avinashxx3** [comment]
Moreover, things like "naming the database in a particular way for the software to work" and "changing port number before running MySQL in XAMPP" are not mentioned.

**Comment by udaykiran183** [comment]
We too had trouble with the setup of XAMPP. We wish to update README to fully detail the steps of the setup. As your group has got to running the project, we will leave this issue for later. For now we wish to find and fix the bugs regarding the Requirements of the software.
