### ISSUE TITLE
Different styles of display in clubs and events list

### ISSUE THREAD

**Issue by avinashxx3** [udaykiran183/CLUBS_IITK#3]
2 of the clubs on the clubs' list, namely Astronomy club and Dramatics, have a bug in displaying their images.

**Comment by avinashxx3** [comment]
Same goes for the list of events.

**Comment by avinashxx3** [comment]
![image](https://user-images.githubusercontent.com/76612206/163727036-526e8a71-466d-4783-b336-40c88544d158.png)

**Comment by udaykiran183** [comment]
> 2 of the clubs on the clubs' list, namely Astronomy club and Dramatics, have a bug in displaying their images.

The Clubs and Events are added using the templates for a club and an event, So a bug in one should imply a bug in all, but could be an issue of the image not getting uploaded while adding the club or the event.

**Comment by udaykiran183** [comment]
> > 2 of the clubs on the clubs' list, namely Astronomy club and Dramatics, have a bug in displaying their images.
> 
> The Clubs and Events are added using the templates for a club and an event, So a bug in one should imply a bug in all, but could be an issue of the image not getting uploaded while adding the club or the event.

It is probably the case that the images are not being rendered properly on your side. It is working fine on our side.
