### ISSUE TITLE
Unknown warnings in Registration page of admin

### ISSUE THREAD

**Issue by avinashxx3** [udaykiran183/CLUBS_IITK#4]
Undefined and irrelevant warnings on the registrations page come up which are of no use to the general user.
![image](https://user-images.githubusercontent.com/76612206/163727009-cdc9249c-2f40-41fb-8523-e73db0266100.png)

**Comment by udaykiran183** [comment]
The previously uploaded SQL file was not the correct(most recent) one. I have uploaded the correct file.

**Comment by udaykiran183** [comment]
> The previously uploaded SQL file was not the correct(most recent) one. I have uploaded the correct file.

We had added the 'interest' column at the last moment and the SQL file was not exported after this change. That should be the reason for the error.
