### ISSUE TITLE
Root password issue in SignUp page

### ISSUE THREAD

**Issue by avinashxx3** [udaykiran183/CLUBS_IITK#5]
Exception caught in the root password. Either the root password given is wrong or there is some other bug.
![image](https://user-images.githubusercontent.com/76612206/163727641-c1f35596-acd8-4204-bfe6-4d4e91eed8d3.png)

**Comment by udaykiran183** [comment]
The root password should be 'root' for the MySQL account in your PC or you could try changing the password from 'root' to the password for your MySQL account in your PC.

**Comment by avinashxx3** [comment]
Well then, that should be explicitely mentioned in the readme file. A general user isn't expected to know such technicalities.

**Comment by udaykiran183** [comment]
We too had trouble with the setup of XAMPP. We wish to update README to fully detail the steps of the setup. As your group has got to running the project, we will leave this issue for later. For now we wish to find and fix the bugs regarding the Requirement Document.
